<?php

use App\Http\Controllers\Admin\AcademicSessionController;
use App\Http\Controllers\Admin\DesignationController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SchoolClassController;
use App\Http\Controllers\Admin\SchoolProfileController;
use App\Http\Controllers\Admin\GuardianController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\StaffController;
use App\Http\Controllers\Admin\StudentController;
use App\Http\Controllers\Admin\StaffDepartmentController;
use App\Http\Controllers\Admin\SubjectController;
use App\Http\Controllers\Admin\TeacherController;
use App\Http\Controllers\Admin\TeacherSubjectAssignmentController;
use App\Http\Controllers\Admin\AttendanceSessionController;
use App\Http\Controllers\Admin\StudentAcademicAssignmentController;
use App\Http\Controllers\Admin\ClassRoutineController;
use App\Http\Controllers\Admin\ExamController;
use App\Http\Controllers\Admin\ExamTypeController;
use App\Http\Controllers\Admin\MarksEntryController;
use App\Http\Controllers\Admin\GradeScaleController;
use App\Http\Controllers\Admin\ResultController;
use App\Http\Controllers\Auth\AdminAuthController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function () {
    Route::post('login', [AdminAuthController::class, 'login']);
    Route::middleware('auth:sanctum')->group(function () {
        Route::post('logout', [AdminAuthController::class, 'logout']);
        Route::get('me', [AdminAuthController::class, 'me']);
        Route::get('roles', [RoleController::class, 'index']);
        Route::get('roles/{role}', [RoleController::class, 'show']);
        Route::get('permissions', [PermissionController::class, 'index']);
        Route::get('school-profile', [SchoolProfileController::class, 'show']);
        Route::post('school-profile', [SchoolProfileController::class, 'updateProfile']);
        Route::get('school-settings', [SchoolProfileController::class, 'getSettings']);
        Route::put('school-settings', [SchoolProfileController::class, 'updateSettings']);
        Route::get('academic-sessions', [AcademicSessionController::class, 'index']);
        Route::post('academic-sessions', [AcademicSessionController::class, 'store']);
        Route::post('academic-sessions/generate-code', [AcademicSessionController::class, 'generateCode']);
        Route::get('academic-sessions/{academic_session}', [AcademicSessionController::class, 'show']);
        Route::put('academic-sessions/{academic_session}', [AcademicSessionController::class, 'update']);
        Route::post('academic-sessions/{academic_session}/set-current', [AcademicSessionController::class, 'setCurrent']);
        Route::get('classes', [SchoolClassController::class, 'index']);
        Route::post('classes', [SchoolClassController::class, 'store']);
        Route::get('classes/{school_class}', [SchoolClassController::class, 'show']);
        Route::put('classes/{school_class}', [SchoolClassController::class, 'update']);
        Route::get('sections', [SectionController::class, 'index']);
        Route::post('sections', [SectionController::class, 'store']);
        Route::get('sections/{section}', [SectionController::class, 'show']);
        Route::put('sections/{section}', [SectionController::class, 'update']);
        Route::get('subjects', [SubjectController::class, 'index']);
        Route::post('subjects', [SubjectController::class, 'store']);
        Route::get('subjects/{subject}', [SubjectController::class, 'show']);
        Route::put('subjects/{subject}', [SubjectController::class, 'update']);
        Route::get('staff-departments', [StaffDepartmentController::class, 'index']);
        Route::post('staff-departments', [StaffDepartmentController::class, 'store']);
        Route::put('staff-departments/{staff_department}', [StaffDepartmentController::class, 'update']);
        Route::get('designations', [DesignationController::class, 'index']);
        Route::post('designations', [DesignationController::class, 'store']);
        Route::put('designations/{designation}', [DesignationController::class, 'update']);
        Route::get('staffs', [StaffController::class, 'index']);
        Route::post('staffs', [StaffController::class, 'store']);
        Route::get('staffs/{staff}', [StaffController::class, 'show']);
        Route::put('staffs/{staff}', [StaffController::class, 'update']);
        Route::get('teachers', [TeacherController::class, 'index']);
        Route::post('teachers', [TeacherController::class, 'store']);
        Route::get('teachers/{teacher}', [TeacherController::class, 'show']);
        Route::put('teachers/{teacher}', [TeacherController::class, 'update']);
        Route::get('students', [StudentController::class, 'index']);
        Route::post('students', [StudentController::class, 'store']);
        Route::get('students/{student}', [StudentController::class, 'show']);
        Route::put('students/{student}', [StudentController::class, 'update']);
        Route::post('students/{student}/guardians', [StudentController::class, 'attachGuardian']);
        Route::get('guardians', [GuardianController::class, 'index']);
        Route::post('guardians', [GuardianController::class, 'store']);
        Route::put('guardians/{student_guardian}', [GuardianController::class, 'update']);
        Route::get('teacher-subject-assignments', [TeacherSubjectAssignmentController::class, 'index']);
        Route::post('teacher-subject-assignments', [TeacherSubjectAssignmentController::class, 'store']);
        Route::get('teacher-subject-assignments/{teacher_subject_assignment}', [TeacherSubjectAssignmentController::class, 'show']);
        Route::put('teacher-subject-assignments/{teacher_subject_assignment}', [TeacherSubjectAssignmentController::class, 'update']);
        Route::get('student-academic-assignments', [StudentAcademicAssignmentController::class, 'index']);
        Route::post('student-academic-assignments', [StudentAcademicAssignmentController::class, 'store']);
        Route::get('attendance-sessions', [AttendanceSessionController::class, 'index']);
        Route::get('attendance-sessions/eligible-students', [AttendanceSessionController::class, 'eligibleStudents']);
        Route::post('attendance-sessions', [AttendanceSessionController::class, 'store']);
        Route::get('attendance-sessions/{attendance_session}', [AttendanceSessionController::class, 'show']);
        Route::put('attendance-sessions/{attendance_session}', [AttendanceSessionController::class, 'update']);
        Route::get('class-routines', [ClassRoutineController::class, 'index']);
        Route::post('class-routines', [ClassRoutineController::class, 'store']);
        Route::get('class-routines/{class_routine}', [ClassRoutineController::class, 'show']);
        Route::put('class-routines/{class_routine}', [ClassRoutineController::class, 'update']);
        Route::get('exam-types', [ExamTypeController::class, 'index']);
        Route::post('exam-types', [ExamTypeController::class, 'store']);
        Route::put('exam-types/{exam_type}', [ExamTypeController::class, 'update']);
        Route::get('exams', [ExamController::class, 'index']);
        Route::post('exams', [ExamController::class, 'store']);
        Route::get('exams/{exam}', [ExamController::class, 'show']);
        Route::put('exams/{exam}', [ExamController::class, 'update']);
        Route::get('marks-entry', [MarksEntryController::class, 'index']);
        Route::get('marks-entry/eligible-students', [MarksEntryController::class, 'eligibleStudents']);
        Route::get('marks-entry/subjects-for-context', [MarksEntryController::class, 'subjectsForContext']);
        Route::get('marks-entry/subject-config', [MarksEntryController::class, 'subjectConfig']);
        Route::get('marks-entry/detail', [MarksEntryController::class, 'show']);
        Route::post('marks-entry', [MarksEntryController::class, 'store']);
        Route::get('grade-scales', [GradeScaleController::class, 'index']);
        Route::post('grade-scales', [GradeScaleController::class, 'store']);
        Route::get('grade-scales/{grade_scale}', [GradeScaleController::class, 'show']);
        Route::put('grade-scales/{grade_scale}', [GradeScaleController::class, 'update']);
        Route::get('results', [ResultController::class, 'index']);
        Route::post('results/generate', [ResultController::class, 'generate']);
        Route::get('results/{result_summary}', [ResultController::class, 'show']);
    });
});
