<?php

use App\Http\Controllers\Admin\AcademicSessionController;
use App\Http\Controllers\Admin\DesignationController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SchoolClassController;
use App\Http\Controllers\Admin\SchoolProfileController;
use App\Http\Controllers\Admin\GuardianController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\StaffController;
use App\Http\Controllers\Admin\StudentController;
use App\Http\Controllers\Admin\StaffDepartmentController;
use App\Http\Controllers\Admin\SubjectController;
use App\Http\Controllers\Admin\TeacherController;
use App\Http\Controllers\Admin\TeacherSubjectAssignmentController;
use App\Http\Controllers\Admin\AttendanceSessionController;
use App\Http\Controllers\Admin\StudentAcademicAssignmentController;
use App\Http\Controllers\Admin\ClassRoutineController;
use App\Http\Controllers\Admin\ExamController;
use App\Http\Controllers\Admin\ExamTypeController;
use App\Http\Controllers\Admin\MarksEntryController;
use App\Http\Controllers\Admin\GradeScaleController;
use App\Http\Controllers\Admin\ResultController;
use App\Http\Controllers\Admin\NoticeController;
use App\Http\Controllers\Admin\NoticeCategoryController;
use App\Http\Controllers\Admin\NewsCategoryController;
use App\Http\Controllers\Admin\NewsPostController;
use App\Http\Controllers\Admin\EventCategoryController;
use App\Http\Controllers\Admin\EventController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\GalleryItemController;
use App\Http\Controllers\Admin\DownloadCategoryController;
use App\Http\Controllers\Admin\DownloadController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\HomepageSectionController;
use App\Http\Controllers\Admin\ActivityLogController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\SystemBackupController;
use App\Http\Controllers\Admin\SystemMaintenanceController;
use App\Http\Controllers\Admin\SystemMonitoringController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminGuideCategoryController;
use App\Http\Controllers\Admin\AdminGuideController;
use App\Http\Controllers\Admin\AdminHelpController;
use App\Http\Controllers\Auth\AdminAuthController;
use App\Http\Controllers\Auth\StudentAuthController;
use App\Http\Controllers\Auth\TeacherAuthController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function () {
    Route::post('login', [AdminAuthController::class, 'login'])->middleware('web');
    Route::middleware('auth:sanctum')->group(function () {
        Route::post('logout', [AdminAuthController::class, 'logout'])->middleware('web');
        Route::get('me', [AdminAuthController::class, 'me']);
        Route::get('dashboard', [DashboardController::class, 'index']);
        Route::get('users/options/roles', [UserController::class, 'optionsRoles']);
        Route::get('users/options/linkable-entities', [UserController::class, 'optionsLinkableEntities']);
        Route::get('users', [UserController::class, 'index']);
        Route::post('users', [UserController::class, 'store']);
        Route::get('users/{user}', [UserController::class, 'show']);
        Route::put('users/{user}', [UserController::class, 'update']);
        Route::delete('users/{user}', [UserController::class, 'destroy']);
        Route::post('users/{user}/activate', [UserController::class, 'activate']);
        Route::post('users/{user}/deactivate', [UserController::class, 'deactivate']);
        Route::post('users/{user}/reset-password', [UserController::class, 'resetPassword']);
        Route::get('roles', [RoleController::class, 'index']);
        Route::post('roles', [RoleController::class, 'store']);
        Route::get('roles/{role}', [RoleController::class, 'show']);
        Route::put('roles/{role}', [RoleController::class, 'update']);
        Route::delete('roles/{role}', [RoleController::class, 'destroy']);
        Route::get('roles/{role}/permissions', [RoleController::class, 'getPermissions']);
        Route::post('roles/{role}/permissions', [RoleController::class, 'syncPermissions']);
        Route::get('permissions', [PermissionController::class, 'index']);
        Route::post('permissions', [PermissionController::class, 'store']);
        Route::get('permissions/{permission}', [PermissionController::class, 'show']);
        Route::put('permissions/{permission}', [PermissionController::class, 'update']);
        Route::delete('permissions/{permission}', [PermissionController::class, 'destroy']);
        Route::get('school-profile', [SchoolProfileController::class, 'show']);
        Route::post('school-profile', [SchoolProfileController::class, 'updateProfile']);
        Route::get('school-settings', [SchoolProfileController::class, 'getSettings']);
        Route::put('school-settings', [SchoolProfileController::class, 'updateSettings']);
        Route::get('academic-sessions', [AcademicSessionController::class, 'index']);
        Route::post('academic-sessions', [AcademicSessionController::class, 'store']);
        Route::post('academic-sessions/generate-code', [AcademicSessionController::class, 'generateCode']);
        Route::get('academic-sessions/{academic_session}', [AcademicSessionController::class, 'show']);
        Route::put('academic-sessions/{academic_session}', [AcademicSessionController::class, 'update']);
        Route::post('academic-sessions/{academic_session}/set-current', [AcademicSessionController::class, 'setCurrent']);
        Route::get('classes', [SchoolClassController::class, 'index']);
        Route::post('classes', [SchoolClassController::class, 'store']);
        Route::post('classes/generate-code', [SchoolClassController::class, 'generateCode']);
        Route::get('classes/{school_class}', [SchoolClassController::class, 'show']);
        Route::put('classes/{school_class}', [SchoolClassController::class, 'update']);
        Route::get('sections', [SectionController::class, 'index']);
        Route::post('sections', [SectionController::class, 'store']);
        Route::post('sections/generate-code', [SectionController::class, 'generateCode']);
        Route::get('sections/{section}', [SectionController::class, 'show']);
        Route::put('sections/{section}', [SectionController::class, 'update']);
        Route::get('subjects', [SubjectController::class, 'index']);
        Route::post('subjects', [SubjectController::class, 'store']);
        Route::get('subjects/{subject}', [SubjectController::class, 'show']);
        Route::put('subjects/{subject}', [SubjectController::class, 'update']);
        Route::get('staff-departments', [StaffDepartmentController::class, 'index']);
        Route::post('staff-departments', [StaffDepartmentController::class, 'store']);
        Route::put('staff-departments/{staff_department}', [StaffDepartmentController::class, 'update']);
        Route::get('designations', [DesignationController::class, 'index']);
        Route::post('designations', [DesignationController::class, 'store']);
        Route::put('designations/{designation}', [DesignationController::class, 'update']);
        Route::get('staffs', [StaffController::class, 'index']);
        Route::post('staffs', [StaffController::class, 'store']);
        Route::get('staffs/{staff}', [StaffController::class, 'show']);
        Route::put('staffs/{staff}', [StaffController::class, 'update']);
        Route::get('teachers', [TeacherController::class, 'index']);
        Route::post('teachers', [TeacherController::class, 'store']);
        Route::get('teachers/{teacher}', [TeacherController::class, 'show']);
        Route::put('teachers/{teacher}', [TeacherController::class, 'update']);
        Route::get('students', [StudentController::class, 'index']);
        Route::post('students', [StudentController::class, 'store']);
        Route::get('students/{student}', [StudentController::class, 'show']);
        Route::put('students/{student}', [StudentController::class, 'update']);
        Route::post('students/{student}/guardians', [StudentController::class, 'attachGuardian']);
        Route::get('guardians', [GuardianController::class, 'index']);
        Route::post('guardians', [GuardianController::class, 'store']);
        Route::put('guardians/{student_guardian}', [GuardianController::class, 'update']);
        Route::get('teacher-subject-assignments', [TeacherSubjectAssignmentController::class, 'index']);
        Route::post('teacher-subject-assignments', [TeacherSubjectAssignmentController::class, 'store']);
        Route::get('teacher-subject-assignments/{teacher_subject_assignment}', [TeacherSubjectAssignmentController::class, 'show']);
        Route::put('teacher-subject-assignments/{teacher_subject_assignment}', [TeacherSubjectAssignmentController::class, 'update']);
        Route::get('student-academic-assignments', [StudentAcademicAssignmentController::class, 'index']);
        Route::post('student-academic-assignments', [StudentAcademicAssignmentController::class, 'store']);
        Route::get('student-academic-assignments/{student_academic_assignment}', [StudentAcademicAssignmentController::class, 'show']);
        Route::put('student-academic-assignments/{student_academic_assignment}', [StudentAcademicAssignmentController::class, 'update']);
        Route::get('attendance-sessions', [AttendanceSessionController::class, 'index']);
        Route::get('attendance-sessions/eligible-students', [AttendanceSessionController::class, 'eligibleStudents']);
        Route::post('attendance-sessions', [AttendanceSessionController::class, 'store']);
        Route::get('attendance-sessions/{attendance_session}', [AttendanceSessionController::class, 'show']);
        Route::put('attendance-sessions/{attendance_session}', [AttendanceSessionController::class, 'update']);
        Route::get('class-routines', [ClassRoutineController::class, 'index']);
        Route::post('class-routines', [ClassRoutineController::class, 'store']);
        Route::get('class-routines/{class_routine}', [ClassRoutineController::class, 'show']);
        Route::put('class-routines/{class_routine}', [ClassRoutineController::class, 'update']);
        Route::get('exam-types', [ExamTypeController::class, 'index']);
        Route::post('exam-types', [ExamTypeController::class, 'store']);
        Route::put('exam-types/{exam_type}', [ExamTypeController::class, 'update']);
        Route::get('exams', [ExamController::class, 'index']);
        Route::post('exams', [ExamController::class, 'store']);
        Route::get('exams/{exam}', [ExamController::class, 'show']);
        Route::put('exams/{exam}', [ExamController::class, 'update']);
        Route::get('marks-entry', [MarksEntryController::class, 'index']);
        Route::get('marks-entry/eligible-students', [MarksEntryController::class, 'eligibleStudents']);
        Route::get('marks-entry/subjects-for-context', [MarksEntryController::class, 'subjectsForContext']);
        Route::get('marks-entry/subject-config', [MarksEntryController::class, 'subjectConfig']);
        Route::get('marks-entry/detail', [MarksEntryController::class, 'show']);
        Route::post('marks-entry', [MarksEntryController::class, 'store']);
        Route::post('marks-entry/reopen', [MarksEntryController::class, 'reopen']);
        Route::get('grade-scales', [GradeScaleController::class, 'index']);
        Route::post('grade-scales', [GradeScaleController::class, 'store']);
        Route::get('grade-scales/{grade_scale}', [GradeScaleController::class, 'show']);
        Route::put('grade-scales/{grade_scale}', [GradeScaleController::class, 'update']);
        Route::get('results', [ResultController::class, 'index']);
        Route::post('results/generate', [ResultController::class, 'generate']);
        Route::get('results/{result_summary}', [ResultController::class, 'show']);
        Route::get('notice-categories', [NoticeCategoryController::class, 'index']);
        Route::get('notices', [NoticeController::class, 'index']);
        Route::post('notices', [NoticeController::class, 'store']);
        Route::get('notices/{notice}', [NoticeController::class, 'show']);
        Route::put('notices/{notice}', [NoticeController::class, 'update']);
        Route::delete('notices/{notice}', [NoticeController::class, 'destroy']);
        Route::post('notices/{notice}/publish', [NoticeController::class, 'publish']);
        Route::post('notices/{notice}/unpublish', [NoticeController::class, 'unpublish']);
        Route::get('news-categories', [NewsCategoryController::class, 'index']);
        Route::get('news-posts', [NewsPostController::class, 'index']);
        Route::post('news-posts', [NewsPostController::class, 'store']);
        Route::get('news-posts/{news_post}', [NewsPostController::class, 'show']);
        Route::put('news-posts/{news_post}', [NewsPostController::class, 'update']);
        Route::delete('news-posts/{news_post}', [NewsPostController::class, 'destroy']);
        Route::post('news-posts/{news_post}/publish', [NewsPostController::class, 'publish']);
        Route::post('news-posts/{news_post}/unpublish', [NewsPostController::class, 'unpublish']);
        Route::get('event-categories', [EventCategoryController::class, 'index']);
        Route::get('events', [EventController::class, 'index']);
        Route::post('events', [EventController::class, 'store']);
        Route::get('events/{event}', [EventController::class, 'show']);
        Route::put('events/{event}', [EventController::class, 'update']);
        Route::delete('events/{event}', [EventController::class, 'destroy']);
        Route::post('events/{event}/publish', [EventController::class, 'publish']);
        Route::post('events/{event}/unpublish', [EventController::class, 'unpublish']);
        Route::get('galleries', [GalleryController::class, 'index']);
        Route::post('galleries', [GalleryController::class, 'store']);
        Route::get('galleries/{gallery}', [GalleryController::class, 'show']);
        Route::put('galleries/{gallery}', [GalleryController::class, 'update']);
        Route::delete('galleries/{gallery}', [GalleryController::class, 'destroy']);
        Route::post('galleries/{gallery}/publish', [GalleryController::class, 'publish']);
        Route::post('galleries/{gallery}/unpublish', [GalleryController::class, 'unpublish']);
        Route::post('galleries/{gallery}/items', [GalleryItemController::class, 'store']);
        Route::post('gallery-items/reorder', [GalleryItemController::class, 'reorder']);
        Route::put('gallery-items/{gallery_item}', [GalleryItemController::class, 'update']);
        Route::delete('gallery-items/{gallery_item}', [GalleryItemController::class, 'destroy']);
        Route::get('download-categories', [DownloadCategoryController::class, 'index']);
        Route::get('downloads', [DownloadController::class, 'index']);
        Route::post('downloads', [DownloadController::class, 'store']);
        Route::get('downloads/{download}', [DownloadController::class, 'show']);
        Route::put('downloads/{download}', [DownloadController::class, 'update']);
        Route::delete('downloads/{download}', [DownloadController::class, 'destroy']);
        Route::post('downloads/{download}/publish', [DownloadController::class, 'publish']);
        Route::post('downloads/{download}/unpublish', [DownloadController::class, 'unpublish']);
        Route::get('pages', [PageController::class, 'index']);
        Route::post('pages', [PageController::class, 'store']);
        Route::get('pages/{page}', [PageController::class, 'show']);
        Route::put('pages/{page}', [PageController::class, 'update']);
        Route::delete('pages/{page}', [PageController::class, 'destroy']);
        Route::post('pages/{page}/publish', [PageController::class, 'publish']);
        Route::post('pages/{page}/unpublish', [PageController::class, 'unpublish']);
        Route::get('banners', [BannerController::class, 'index']);
        Route::post('banners', [BannerController::class, 'store']);
        Route::post('banners/reorder', [BannerController::class, 'reorder']);
        Route::get('banners/{banner}', [BannerController::class, 'show']);
        Route::put('banners/{banner}', [BannerController::class, 'update']);
        Route::delete('banners/{banner}', [BannerController::class, 'destroy']);
        Route::get('homepage-sections', [HomepageSectionController::class, 'index']);
        Route::post('homepage-sections', [HomepageSectionController::class, 'store']);
        Route::post('homepage-sections/reorder', [HomepageSectionController::class, 'reorder']);
        Route::get('homepage-sections/{homepage_section}', [HomepageSectionController::class, 'show']);
        Route::put('homepage-sections/{homepage_section}', [HomepageSectionController::class, 'update']);
        Route::delete('homepage-sections/{homepage_section}', [HomepageSectionController::class, 'destroy']);
        Route::post('homepage-sections/{homepage_section}/toggle-visibility', [HomepageSectionController::class, 'toggleVisibility']);
        Route::get('activity-logs', [ActivityLogController::class, 'index']);
        Route::get('activity-logs/filter-options', [ActivityLogController::class, 'filterOptions']);
        Route::get('activity-logs/{activity_log}', [ActivityLogController::class, 'show']);
        Route::get('system-monitoring/overview', [SystemMonitoringController::class, 'overview']);
        Route::get('system-monitoring/login-history', [SystemMonitoringController::class, 'loginHistory']);
        Route::get('system-monitoring/active-sessions', [SystemMonitoringController::class, 'activeSessions']);
        Route::get('system-maintenance/status', [SystemMaintenanceController::class, 'status']);
        Route::post('system-maintenance/enable', [SystemMaintenanceController::class, 'enable']);
        Route::post('system-maintenance/disable', [SystemMaintenanceController::class, 'disable']);
        Route::get('system-backups', [SystemBackupController::class, 'index']);
        Route::post('system-backups/generate', [SystemBackupController::class, 'generate']);
        Route::get('system-backups/{system_backup}', [SystemBackupController::class, 'show']);
        Route::get('admin-guide-categories', [AdminGuideCategoryController::class, 'index']);
        Route::post('admin-guide-categories', [AdminGuideCategoryController::class, 'store']);
        Route::post('admin-guide-categories/reorder', [AdminGuideCategoryController::class, 'reorder']);
        Route::get('admin-guide-categories/{admin_guide_category}', [AdminGuideCategoryController::class, 'show']);
        Route::put('admin-guide-categories/{admin_guide_category}', [AdminGuideCategoryController::class, 'update']);
        Route::delete('admin-guide-categories/{admin_guide_category}', [AdminGuideCategoryController::class, 'destroy']);
        Route::get('admin-guides', [AdminGuideController::class, 'index']);
        Route::post('admin-guides', [AdminGuideController::class, 'store']);
        Route::get('admin-guides/{admin_guide}', [AdminGuideController::class, 'show']);
        Route::put('admin-guides/{admin_guide}', [AdminGuideController::class, 'update']);
        Route::delete('admin-guides/{admin_guide}', [AdminGuideController::class, 'destroy']);
        Route::get('help/categories', [AdminHelpController::class, 'categories']);
        Route::get('help/guides', [AdminHelpController::class, 'guides']);
        Route::get('help/guides/{slug}', [AdminHelpController::class, 'guideBySlug']);
        Route::get('help/search', [AdminHelpController::class, 'search']);
    });
});

// Teachers Portal API
Route::prefix('teacher')->group(function () {
    Route::post('login', [TeacherAuthController::class, 'login'])->middleware('web');
    Route::middleware(['auth:sanctum', 'teacher'])->group(function () {
        Route::post('logout', [TeacherAuthController::class, 'logout'])->middleware('web');
        Route::get('me', [TeacherAuthController::class, 'me']);
        Route::get('dashboard', [\App\Http\Controllers\Teacher\DashboardController::class, 'index']);
        Route::get('routine', [\App\Http\Controllers\Teacher\RoutineController::class, 'index']);
        Route::get('attendance', [\App\Http\Controllers\Teacher\AttendanceController::class, 'index']);
        Route::post('attendance', [\App\Http\Controllers\Teacher\AttendanceController::class, 'store']);
        Route::get('attendance/{attendance_session}', [\App\Http\Controllers\Teacher\AttendanceController::class, 'show']);
        Route::put('attendance/{attendance_session}', [\App\Http\Controllers\Teacher\AttendanceController::class, 'update']);
        Route::post('attendance/{attendance_session}/submit', [\App\Http\Controllers\Teacher\AttendanceController::class, 'submit']);
        Route::get('students', [\App\Http\Controllers\Teacher\StudentController::class, 'index']);
        Route::get('homework', [\App\Http\Controllers\Teacher\HomeworkController::class, 'index']);
        Route::post('homework', [\App\Http\Controllers\Teacher\HomeworkController::class, 'store']);
        Route::get('homework/{homework}', [\App\Http\Controllers\Teacher\HomeworkController::class, 'show']);
        Route::put('homework/{homework}', [\App\Http\Controllers\Teacher\HomeworkController::class, 'update']);
        Route::delete('homework/{homework}', [\App\Http\Controllers\Teacher\HomeworkController::class, 'destroy']);
        Route::get('lesson-plans', [\App\Http\Controllers\Teacher\LessonPlanController::class, 'index']);
        Route::post('lesson-plans', [\App\Http\Controllers\Teacher\LessonPlanController::class, 'store']);
        Route::get('lesson-plans/{lesson_plan}', [\App\Http\Controllers\Teacher\LessonPlanController::class, 'show']);
        Route::put('lesson-plans/{lesson_plan}', [\App\Http\Controllers\Teacher\LessonPlanController::class, 'update']);
        Route::delete('lesson-plans/{lesson_plan}', [\App\Http\Controllers\Teacher\LessonPlanController::class, 'destroy']);
        Route::get('exams', [\App\Http\Controllers\Teacher\ExamController::class, 'index']);
        Route::get('exams/filter-options', [\App\Http\Controllers\Teacher\ExamController::class, 'filterOptions']);
        Route::get('exams/{exam}', [\App\Http\Controllers\Teacher\ExamController::class, 'show']);
        Route::get('exams/{exam}/summary', [\App\Http\Controllers\Teacher\ExamSummaryController::class, 'show']);
        Route::get('exams/{exam}/marks-entry/contexts', [\App\Http\Controllers\Teacher\MarksEntryController::class, 'contexts']);
        Route::get('exams/{exam}/marks-entry/contexts-with-status', [\App\Http\Controllers\Teacher\MarksEntryController::class, 'contextsWithStatus']);
        Route::get('exams/{exam}/marks-entry', [\App\Http\Controllers\Teacher\MarksEntryController::class, 'show']);
        Route::put('exams/{exam}/marks-entry', [\App\Http\Controllers\Teacher\MarksEntryController::class, 'update']);
        Route::post('exams/{exam}/marks-entry/submit', [\App\Http\Controllers\Teacher\MarksEntryController::class, 'submit']);
        Route::get('notices/category-options', [\App\Http\Controllers\Teacher\NoticeController::class, 'categoryOptions']);
        Route::get('notices', [\App\Http\Controllers\Teacher\NoticeController::class, 'index']);
        Route::get('notices/{notice}', [\App\Http\Controllers\Teacher\NoticeController::class, 'show']);
        Route::get('events/category-options', [\App\Http\Controllers\Teacher\EventController::class, 'categoryOptions']);
        Route::get('events', [\App\Http\Controllers\Teacher\EventController::class, 'index']);
        Route::get('events/{event}', [\App\Http\Controllers\Teacher\EventController::class, 'show']);
        Route::get('leave-requests', [\App\Http\Controllers\Teacher\LeaveRequestController::class, 'index']);
        Route::post('leave-requests', [\App\Http\Controllers\Teacher\LeaveRequestController::class, 'store']);
        Route::get('leave-requests/{leave_request}', [\App\Http\Controllers\Teacher\LeaveRequestController::class, 'show']);
        Route::put('leave-requests/{leave_request}', [\App\Http\Controllers\Teacher\LeaveRequestController::class, 'update']);
        Route::post('leave-requests/{leave_request}', [\App\Http\Controllers\Teacher\LeaveRequestController::class, 'update']);
        Route::delete('leave-requests/{leave_request}', [\App\Http\Controllers\Teacher\LeaveRequestController::class, 'destroy']);
        Route::get('messages/recipients', [\App\Http\Controllers\Teacher\MessageController::class, 'recipients']);
        Route::get('messages', [\App\Http\Controllers\Teacher\MessageController::class, 'index']);
        Route::post('messages', [\App\Http\Controllers\Teacher\MessageController::class, 'store']);
        Route::get('conversations/{conversation}', [\App\Http\Controllers\Teacher\MessageController::class, 'show']);
        Route::get('conversations/{conversation}/messages', [\App\Http\Controllers\Teacher\MessageController::class, 'messages']);
        Route::post('conversations/{conversation}/mark-read', [\App\Http\Controllers\Teacher\MessageController::class, 'markRead']);
        Route::post('conversations/{conversation}/messages', [\App\Http\Controllers\Teacher\MessageController::class, 'reply']);
        Route::get('conversations/{conversation}/messages/{message}/attachments/{attachment}/download', [\App\Http\Controllers\Teacher\MessageController::class, 'downloadAttachment'])
            ->whereNumber(['conversation', 'message', 'attachment'])
            ->name('teacher.message.attachment.download');
        Route::get('reports/attendance-summary', [\App\Http\Controllers\Teacher\ReportController::class, 'attendanceSummary']);
        Route::get('reports/marks-sheet', [\App\Http\Controllers\Teacher\ReportController::class, 'marksSheet']);
        Route::get('reports/homework-summary', [\App\Http\Controllers\Teacher\ReportController::class, 'homeworkSummary']);
        Route::get('analytics/attendance-trends', [\App\Http\Controllers\Teacher\AnalyticsController::class, 'attendanceTrends']);
        Route::get('analytics/homework-trends', [\App\Http\Controllers\Teacher\AnalyticsController::class, 'homeworkTrends']);
        Route::get('analytics/marks-trends', [\App\Http\Controllers\Teacher\AnalyticsController::class, 'marksTrends']);
        Route::get('analytics/students-needing-attention', [\App\Http\Controllers\Teacher\AnalyticsController::class, 'studentsNeedingAttention']);
        Route::get('notifications', [\App\Http\Controllers\Teacher\NotificationController::class, 'index']);
        Route::get('notifications/unread-count', [\App\Http\Controllers\Teacher\NotificationController::class, 'unreadCount']);
        Route::patch('notifications/{teacher_notification}', [\App\Http\Controllers\Teacher\NotificationController::class, 'markAsRead']);
        Route::post('notifications/mark-all-read', [\App\Http\Controllers\Teacher\NotificationController::class, 'markAllAsRead']);
        Route::get('learning-materials/assignment-options', [\App\Http\Controllers\Teacher\LearningMaterialController::class, 'assignmentOptions']);
        Route::get('learning-materials', [\App\Http\Controllers\Teacher\LearningMaterialController::class, 'index']);
        Route::post('learning-materials', [\App\Http\Controllers\Teacher\LearningMaterialController::class, 'store']);
        Route::get('learning-materials/{learning_material}', [\App\Http\Controllers\Teacher\LearningMaterialController::class, 'show']);
        Route::put('learning-materials/{learning_material}', [\App\Http\Controllers\Teacher\LearningMaterialController::class, 'update']);
        Route::delete('learning-materials/{learning_material}', [\App\Http\Controllers\Teacher\LearningMaterialController::class, 'destroy']);
    });
});

// Student Portal API
Route::prefix('student')->group(function () {
    Route::post('login', [StudentAuthController::class, 'login'])->middleware('web');
    Route::middleware(['auth:sanctum', 'student'])->group(function () {
        Route::post('logout', [StudentAuthController::class, 'logout'])->middleware('web');
        Route::get('me', [StudentAuthController::class, 'me']);
        Route::get('dashboard', [\App\Http\Controllers\Student\StudentDashboardController::class, 'index']);
        Route::get('profile', [\App\Http\Controllers\Student\StudentProfileController::class, 'show']);
        Route::get('routine', [\App\Http\Controllers\Student\StudentRoutineController::class, 'index']);
        Route::get('notices', [\App\Http\Controllers\Student\StudentNoticeController::class, 'index']);
        Route::get('notices/{notice}', [\App\Http\Controllers\Student\StudentNoticeController::class, 'show']);
        Route::get('homework', [\App\Http\Controllers\Student\StudentHomeworkController::class, 'index']);
        Route::get('homework/{homework}', [\App\Http\Controllers\Student\StudentHomeworkController::class, 'show']);
        Route::post('homework/{homework}/submit', [\App\Http\Controllers\Student\StudentHomeworkController::class, 'submit']);
        Route::get('homework/{homework}/attachment', [\App\Http\Controllers\Student\StudentHomeworkController::class, 'downloadAttachment']);
        Route::get('results', [\App\Http\Controllers\Student\StudentResultController::class, 'index']);
        Route::get('attendance', [\App\Http\Controllers\Student\StudentAttendanceController::class, 'index']);
        Route::get('materials', [\App\Http\Controllers\Student\StudentLearningMaterialController::class, 'index']);
        Route::get('exams', [\App\Http\Controllers\Student\StudentExamController::class, 'index']);
        Route::get('notifications', [\App\Http\Controllers\Student\StudentNotificationController::class, 'index']);
        Route::get('notifications/unread-count', [\App\Http\Controllers\Student\StudentNotificationController::class, 'unreadCount']);
        Route::patch('notifications/{student_notification}/read', [\App\Http\Controllers\Student\StudentNotificationController::class, 'markAsRead']);
        Route::post('notifications/mark-all-read', [\App\Http\Controllers\Student\StudentNotificationController::class, 'markAllAsRead']);
        Route::get('messages/recipients', [\App\Http\Controllers\Student\StudentMessageController::class, 'recipients']);
        Route::get('messages', [\App\Http\Controllers\Student\StudentMessageController::class, 'index']);
        Route::get('messages/conversations/{conversation}', [\App\Http\Controllers\Student\StudentMessageController::class, 'show']);
        Route::get('messages/conversations/{conversation}/messages', [\App\Http\Controllers\Student\StudentMessageController::class, 'messages']);
        Route::post('messages', [\App\Http\Controllers\Student\StudentMessageController::class, 'store']);
        Route::post('messages/conversations/{conversation}/messages', [\App\Http\Controllers\Student\StudentMessageController::class, 'reply']);
        Route::post('messages/conversations/{conversation}/mark-read', [\App\Http\Controllers\Student\StudentMessageController::class, 'markRead']);
        Route::get('messages/conversations/{conversation}/messages/{message}/attachments/{attachment}/download', [\App\Http\Controllers\Student\StudentMessageController::class, 'downloadAttachment']);
        Route::get('fees', [\App\Http\Controllers\Student\StudentFeeController::class, 'index']);
    });
});
